### ISSUE TITLE
Are you sure the program can run ?

### ISSUE THREAD

**Issue by zwj2017-NK** [ChenJunHero/DroidAPIMiner#1]
I have cloned  the repos on localhost, and ran the api_miner.py, the error message is as follows.
zhuwenjun@zhuwenjun-Vostro-3668:/media/zhuwenjun/a046836e-2436-4362-a0f1-0023db7b7ad4/DroidAPIMiner$ sudo python api_miner.py
Traceback (most recent call last):
  File "api_miner.py", line 4, in <module>
    from external_api import *
  File "/home/chenjun/Desktop/api_miner/external_api.py", line 9, in <module>
  File "/home/chenjun/Desktop/apiMiner/external_api_calls/androguard/core/androconf.py", line 8, in <module>
ImportError: cannot import name __version__

**Comment by alexx384** [comment]
Faced the same problem. Fixed by switch to branch **api_miner** and install **androguard** package:
`pip install androguard`
